# Generated by Django 5.0.3 on 2024-03-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()
    operations = ()