# Generated by Django 5.0.3 on 2024-03-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_create-comment_and_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
